NAME_GROUPS = [
    ["Bäcker", "Mahler", "Müller"],
    ["Sanchez", "Gonzales", "Martinez", "Silva"],
    ["Rahim ", "Yldirim", "Özdak ", "Shahin ", "Ogris "],
    ["Althaus", "Hauser", "Neuhaus"],
    ["Rothstein", "Weißer", "Grüning"],
    ["Kreutzer", "Schiffer", "Fährmann"],
]

JOB_GROUPS = [
    [
        ["Apotheker", "Apothekerin"],
        ["Hausarzt", "Hausärztin"],
        ["Hautarzt", "Hautärztin"],
        ["Kardiologe", "Kardiologin"],
        ["Neurologe", "Neurologin"],
        ["Internist", "Internistin"],
        ["Gastroenterologe", "Gastroenterologin"],
        ["Augenarzt", "Augenärztin"],
        ["Optiker", "Optikerin"],
        ["Zahnarzt", "Zahnärztin"],
    ],
    [
        ["Stylist", "Stylistin"],
        ["Friseur", "Friseurin"],
        ["MakeUp-Artist", "MakeUp-Artist"],
        ["Designer", "Designerin"],
    ],
    [["Schreiner", "Schreinerin"], ["Tischler", "Tischlerin"], ["Maler", "Malerin"]],
    [
        ["Bauarbeiter", "Bauarbeiterin"],
        ["Architekt", "Architektin"],
        ["Bauleiter", "Bauleiterin"],
        ["Klempner", "Klempnerin"],
    ],
    [
        ["Hausmeister", "Hausmeisterin"],
        ["Gärtner", "Gärtnerin"],
        ["Fensterputzer", "Fensterputzerin"],
    ],
    [
        ["Chemiker", "Chemikerin"],
        ["Physiker", "Physikerin"],
        ["Biologe", "Biologin"],
        ["Mathematiker", "Mathematikerin"],
        ["Informatiker", "Informatikerin"],
    ],
    [["Professor", "Professorin"], ["Doktorand", "Doktorandin"], ["HiWi", "HiWi"]],
    [
        ["CEO", "CEO"],
        ["Investor", "Investorin"],
        ["Manager", "Managerin"],
        ["Personalchef", "Personalchefin"],
        ["Filialleiter", "Filialleiterin"],
    ],
]

AGES = [f"Ca. {age} Jahre" for age in [20, 30, 40, 50, 60, 70]]

SYMPTOMS = [
    "Erkältung",
    "Mandelentzündung",
    "Cholera",
    "Gürtelrose",
    "Blutvergiftung",
    "Myokarditis",
    "Sehnenriss",
    "Armbruch",
    "Kieferbruch",
    "Mittelhandbruch",
    "Lungenentzündung",
    "Thrombose",
    "Embolie",
    "Herzinfarkt",
    "Migräne",
    "Ausschlag",
    "Husten",
    "Bandscheibenvorfall",
    "Durchfall",
    "Verstopfung",
    "Gallensteine",
    "Nierensteine",
    "Hepatitis",
    "HIV",
    "Zahnschmerzen",
    "Myalgie",
    "Schlaganfall",
]

SITUATIONS = [
    "in Ambulanz",
    "in Notaufnahme",
    "Notfall",
    "im Krankenwagen",
    "in Intensivstation",
    "in ReHa",
    "in Radiologie",
    "in OP",
    "fröhlich",
    "ehrgeizig",
    "nett",
    "ernst",
    "streng",
    "empfindlich",
    "kritisch",
    "uneinsichtig",
    "verwirrt",
    "unfreundlich",
    "zielstrebig",
    "egoistisch",
    "hilfsbereit",
    "verheiratet",
    "geschieden",
]
